const Erros = {
    USUARIO_JA_EXISTE: "USUARIO_JA_EXISTE",
    USUARIO_NAO_EXISTE: "USUARIO_NAO_EXISTE",
    SENHA_INCORRETA: "SENHA_INCORRETA",
    TOKEN_INVALIDO: "TOKEN_INVALIDO",
} as const

export default Erros
